CREATE SCHEMA AUTHORIZATION REPORT;

CREATE TABLE CHART_GRAPHIC (
		CHART_GRAPHIC_ID NUMBER(11 , 0) NOT NULL,
		CHART_NAME VARCHAR2(60) DEFAULT NULL,
		REPORT_ID NUMBER(11 , 0) DEFAULT NULL,
		X_LABEL VARCHAR2(200) DEFAULT NULL,
		Y_LABEL VARCHAR2(200) DEFAULT NULL,
		LEGEND_LOCATION VARCHAR2(10) DEFAULT NULL,
		CHART_HEIGHT NUMBER(11 , 0) DEFAULT NULL,
		CHART_WIDTH NUMBER(11 , 0) DEFAULT NULL,
		CHART_TYPE VARCHAR2(20) DEFAULT NULL,
		CHART_SUBTYPE VARCHAR2(20) DEFAULT NULL,
		DATA_RANGE_COLUMN VARCHAR2(30) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE COLUMNS (
		COLUMNS_ID NUMBER(11 , 0) NOT NULL,
		REPORT_ID NUMBER(11 , 0) DEFAULT NULL,
		COLUMN_NAME VARCHAR2(50) DEFAULT NULL,
		WIDTH NUMBER(11 , 0) DEFAULT NULL,
		ALIGNMENT VARCHAR2(15) DEFAULT NULL,
		CLASS_TYPE VARCHAR2(100) DEFAULT NULL,
		ORDER_POSITION NUMBER(11 , 0) DEFAULT NULL,
		BAND_TYPE VARCHAR2(10) DEFAULT NULL,
		COLUMN_EXPRESSION VARCHAR2(200) DEFAULT NULL,
		LABEL_WIDTH NUMBER(11 , 0) DEFAULT NULL,
		EVALUATION_TIME VARCHAR2(10) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE CONTEXT_HELP (
		CONTEXT_HELP_ID NUMBER(11 , 0) NOT NULL,
		CONTEXT_HELP VARCHAR2(1000) DEFAULT NULL,
		CONTEXT_FIELD VARCHAR2(50) DEFAULT NULL,
		CONTEXT_FORM VARCHAR2(50) DEFAULT NULL,
		MENU_CONTROL_ID NUMBER(11 , 0) DEFAULT NULL,
		CONTEXT_ACTION VARCHAR2(3) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE CUSTOMER (
		CUSTOMER_ID NUMBER(11 , 0) NOT NULL,
		NAME VARCHAR2(50) DEFAULT NULL,
		ADDRESS1 VARCHAR2(50) DEFAULT NULL,
		ADDRESS2 VARCHAR2(50) DEFAULT NULL,
		CITY VARCHAR2(50) DEFAULT NULL,
		STATE VARCHAR2(2) DEFAULT NULL,
		ZIP_CODE VARCHAR2(8) DEFAULT NULL,
		PHONE VARCHAR2(50) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE DATABASE_TABLE (
		TABLE_ID NUMBER(11 , 0) NOT NULL,
		TABLE_NAME VARCHAR2(50) DEFAULT NULL,
		SCHEMA_NAME VARCHAR2(50) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE FIELDS (
		FIEDLS_ID NUMBER(11 , 0) NOT NULL,
		REPORT_ID NUMBER(11 , 0) DEFAULT NULL,
		FIELD_NAME VARCHAR2(60) DEFAULT NULL,
		FIELD_DESCRIPTION VARCHAR2(80) DEFAULT NULL,
		CLASS_TYPE VARCHAR2(100) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE GROUPS (
		GROUPS_ID NUMBER(11 , 0) NOT NULL,
		REPORT_ID NUMBER(11 , 0) DEFAULT NULL,
		GROUP_NAME VARCHAR2(30) DEFAULT NULL,
		IS_REPRINT_HEADER VARCHAR2(10) DEFAULT NULL,
		GROUP_EXPRESSION VARCHAR2(100) DEFAULT NULL,
		ORDER_POSITION NUMBER(11 , 0) DEFAULT NULL,
		BG_COLOR VARCHAR2(7) DEFAULT NULL,
		FG_COLOR VARCHAR2(7) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE GROUP_COLUMNS (
		GROUP_COLUMNS_ID NUMBER(11 , 0) NOT NULL,
		DESCRIPTION VARCHAR2(30) DEFAULT NULL,
		WIDTH NUMBER(11 , 0) DEFAULT NULL,
		ALIGNMENT VARCHAR2(15) DEFAULT NULL,
		CLASS_TYPE VARCHAR2(100) DEFAULT NULL,
		FIELD_EXPRESSION VARCHAR2(255) DEFAULT NULL,
		ORDER_POSITION NUMBER(11 , 0) DEFAULT NULL,
		BAND_TYPE VARCHAR2(10) DEFAULT NULL,
		GROUPS_ID NUMBER(11 , 0) DEFAULT NULL,
		IS_PRINT_HEADER VARCHAR2(3) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE JAVA_CLASS (
		CLASS_TYPE VARCHAR2(100) NOT NULL
	)
	LOGGING;

CREATE TABLE MENU_CONTROL (
		MENU_CONTROL_ID NUMBER(11 , 0) NOT NULL,
		NAME VARCHAR2(50) DEFAULT NULL,
		DESCRIPTION VARCHAR2(100) DEFAULT NULL,
		ACTIVE VARCHAR2(3) DEFAULT NULL,
		URL VARCHAR2(100) DEFAULT NULL,
		CATEGORY VARCHAR2(30) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE ORDERS (
		ORDERS_ID NUMBER(11 , 0) NOT NULL,
		CUSTOMER_ID NUMBER(11 , 0) DEFAULT NULL,
		ORDE_DATE DATE DEFAULT NULL,
		SELLER VARCHAR2(50) DEFAULT NULL,
		SHIP_ADDRESS1 VARCHAR2(50) DEFAULT NULL,
		SHIP_ADDRESS2 VARCHAR2(50) DEFAULT NULL,
		SHIP_CITY VARCHAR2(50) DEFAULT NULL,
		SHIP_STATE VARCHAR2(2) DEFAULT NULL,
		SHIP_ZIP VARCHAR2(8) DEFAULT NULL,
		SHIP_PHONE VARCHAR2(50) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE ORDERS_ITENS (
		ORDERS_ID NUMBER(11 , 0) DEFAULT NULL,
		PRODUCT_ID NUMBER(11 , 0) DEFAULT NULL,
		QUANTITY NUMBER(11 , 0) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE PARAMETERS (
		PARAMETERS_ID NUMBER(11 , 0) NOT NULL,
		REPORT_ID NUMBER(11 , 0) DEFAULT NULL,
		PRAMETER_NAME VARCHAR2(30) DEFAULT NULL,
		CLASS_TYPE VARCHAR2(100) DEFAULT NULL,
		PARAMETER_DESCRIPTION VARCHAR2(50) DEFAULT NULL,
		IS_REQUIRED VARCHAR2(3) DEFAULT NULL,
		INPUT_TYPE VARCHAR2(20) DEFAULT NULL,
		TABLE_INPUT VARCHAR2(255) DEFAULT NULL,
		FIELD_KEY VARCHAR2(30) DEFAULT NULL,
		FIELD_DISPLAY VARCHAR2(30) DEFAULT NULL,
		SQL_TEXT VARCHAR2(255) DEFAULT NULL,
		RADIO_OPTIONS VARCHAR2(255) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE PRODUCT (
		PRODUCT_ID NUMBER(11 , 0) NOT NULL,
		NAME VARCHAR2(50) DEFAULT NULL,
		AVAILABILITY NUMBER(11 , 0) DEFAULT NULL,
		PRICE NUMBER(12 , 2) DEFAULT NULL,
		CATEGORY VARCHAR2(50) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE REPORT (
		REPORT_ID NUMBER(11 , 0) NOT NULL,
		REPORT_NAME VARCHAR2(50) DEFAULT NULL,
		DESCRIPTION VARCHAR2(100) DEFAULT NULL,
		TITLE VARCHAR2(100) DEFAULT NULL,
		IMAGE VARCHAR2(100) DEFAULT NULL,
		HEADER VARCHAR2(100) DEFAULT NULL,
		FOOTER VARCHAR2(100) DEFAULT NULL,
		SQL_TEXT VARCHAR2(2500) DEFAULT NULL,
		ORIENTATION VARCHAR2(20) DEFAULT NULL,
		PAGE_HEADER VARCHAR2(100) DEFAULT NULL,
		PAGE_FOOTER VARCHAR2(100) DEFAULT NULL,
		SUMMARY VARCHAR2(100) DEFAULT NULL,
		TEMPLATE VARCHAR2(255) DEFAULT NULL,
		JNDI_NAME VARCHAR2(50) DEFAULT NULL,
		CONTEXT_TYPE VARCHAR2(50) DEFAULT NULL,
		DETAIL_COLOR_OFF VARCHAR2(8) DEFAULT NULL,
		DETAIL_COLOR_ON VARCHAR2(8) DEFAULT NULL,
		DETAIL_HEAD_FG_COLOR VARCHAR2(8) DEFAULT NULL,
		DETAIL_HEAD_BG_COLOR VARCHAR2(8) DEFAULT NULL,
		TITLE_FG_COLOR VARCHAR2(8) DEFAULT NULL,
		TITLE_BG_COLOR VARCHAR2(8) DEFAULT NULL,
		JASPER_JRXML BLOB
	)
	LOGGING;

CREATE TABLE SEQUENCE (
		TABLE_NAME VARCHAR2(50) DEFAULT NULL,
		LAST_VALUE NUMBER(11 , 0) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE SERIES_COLUMNS (
		SERIES_COLUMNS_ID NUMBER(11 , 0) NOT NULL,
		CHART_GRAPHIC_ID NUMBER(11 , 0) DEFAULT NULL,
		COLUMN_NAME VARCHAR2(30) DEFAULT NULL,
		COLUMN_TYPE VARCHAR2(1) DEFAULT NULL,
		ORDER_POSITION NUMBER(11 , 0) DEFAULT NULL
	)
	LOGGING;

CREATE TABLE VARIABLES (
		VARIABLES_ID NUMBER(11 , 0) NOT NULL,
		REPORT_ID NUMBER(11 , 0) DEFAULT NULL,
		VARIABLE_NAME VARCHAR2(30) DEFAULT NULL,
		VARIABLE_DESCRIPTION VARCHAR2(30) DEFAULT NULL,
		CLASS_TYPE VARCHAR2(100) DEFAULT NULL,
		RESET_TYPE VARCHAR2(30) DEFAULT NULL,
		INCREMENT_TYPE VARCHAR2(30) DEFAULT NULL,
		RESET_GROUP_ID NUMBER(11 , 0) DEFAULT NULL,
		INCREMENT_GROUP_ID NUMBER(11 , 0) DEFAULT NULL,
		CALCULATION VARCHAR2(30) DEFAULT NULL,
		VARIABLE_EXPRESSION VARCHAR2(255) DEFAULT NULL
	)
	LOGGING;

CREATE UNIQUE INDEX SYS_C0011169
	ON FIELDS
	(FIEDLS_ID		ASC)
	LOGGING;

ALTER TABLE CHART_GRAPHIC ADD CONSTRAINT SYS_C0011158 CHECK ("CHART_GRAPHIC_ID" IS NOT NULL);

ALTER TABLE CHART_GRAPHIC ADD CONSTRAINT SYS_C0011159 PRIMARY KEY
	(CHART_GRAPHIC_ID);

ALTER TABLE COLUMNS ADD CONSTRAINT SYS_C0011161 CHECK ("COLUMNS_ID" IS NOT NULL);

ALTER TABLE COLUMNS ADD CONSTRAINT SYS_C0011162 PRIMARY KEY
	(COLUMNS_ID);

ALTER TABLE CONTEXT_HELP ADD CONSTRAINT SYS_C0011181 CHECK ("CONTEXT_HELP_ID" IS NOT NULL);

ALTER TABLE CONTEXT_HELP ADD CONSTRAINT SYS_C0011182 PRIMARY KEY
	(CONTEXT_HELP_ID);

ALTER TABLE CUSTOMER ADD CONSTRAINT SYS_C0011164 CHECK ("CUSTOMER_ID" IS NOT NULL);

ALTER TABLE CUSTOMER ADD CONSTRAINT SYS_C0011165 PRIMARY KEY
	(CUSTOMER_ID);

ALTER TABLE DATABASE_TABLE ADD CONSTRAINT SYS_C0011166 CHECK ("TABLE_ID" IS NOT NULL);

ALTER TABLE DATABASE_TABLE ADD CONSTRAINT SYS_C0011167 PRIMARY KEY
	(TABLE_ID);

ALTER TABLE FIELDS ADD CONSTRAINT SYS_C0030052 CHECK ("FIEDLS_ID" IS NOT NULL);

ALTER TABLE FIELDS ADD CONSTRAINT SYS_C0011169 PRIMARY KEY
	(FIEDLS_ID);

ALTER TABLE GROUPS ADD CONSTRAINT SYS_C0011171 CHECK ("GROUPS_ID" IS NOT NULL);

ALTER TABLE GROUPS ADD CONSTRAINT SYS_C0011172 PRIMARY KEY
	(GROUPS_ID);

ALTER TABLE GROUP_COLUMNS ADD CONSTRAINT SYS_C0011174 CHECK ("GROUP_COLUMNS_ID" IS NOT NULL);

ALTER TABLE GROUP_COLUMNS ADD CONSTRAINT SYS_C0011175 PRIMARY KEY
	(GROUP_COLUMNS_ID);

ALTER TABLE JAVA_CLASS ADD CONSTRAINT SYS_C0011177 CHECK ("CLASS_TYPE" IS NOT NULL);

ALTER TABLE JAVA_CLASS ADD CONSTRAINT SYS_C0011178 PRIMARY KEY
	(CLASS_TYPE);

ALTER TABLE MENU_CONTROL ADD CONSTRAINT SYS_C0011179 CHECK ("MENU_CONTROL_ID" IS NOT NULL);

ALTER TABLE MENU_CONTROL ADD CONSTRAINT SYS_C0011180 PRIMARY KEY
	(MENU_CONTROL_ID);

ALTER TABLE ORDERS ADD CONSTRAINT SYS_C0011184 CHECK ("ORDERS_ID" IS NOT NULL);

ALTER TABLE ORDERS ADD CONSTRAINT SYS_C0011185 PRIMARY KEY
	(ORDERS_ID);

ALTER TABLE PARAMETERS ADD CONSTRAINT SYS_C0011187 CHECK ("PARAMETERS_ID" IS NOT NULL);

ALTER TABLE PARAMETERS ADD CONSTRAINT SYS_C0011188 PRIMARY KEY
	(PARAMETERS_ID);

ALTER TABLE PRODUCT ADD CONSTRAINT SYS_C0011190 CHECK ("PRODUCT_ID" IS NOT NULL);

ALTER TABLE PRODUCT ADD CONSTRAINT SYS_C0011191 PRIMARY KEY
	(PRODUCT_ID);

ALTER TABLE REPORT ADD CONSTRAINT SYS_C0011156 CHECK ("REPORT_ID" IS NOT NULL);

ALTER TABLE REPORT ADD CONSTRAINT SYS_C0011157 PRIMARY KEY
	(REPORT_ID);

ALTER TABLE SERIES_COLUMNS ADD CONSTRAINT SYS_C0011194 CHECK ("SERIES_COLUMNS_ID" IS NOT NULL);

ALTER TABLE SERIES_COLUMNS ADD CONSTRAINT SYS_C0011195 PRIMARY KEY
	(SERIES_COLUMNS_ID);

ALTER TABLE VARIABLES ADD CONSTRAINT SYS_C0011197 CHECK ("VARIABLES_ID" IS NOT NULL);

ALTER TABLE VARIABLES ADD CONSTRAINT SYS_C0011198 PRIMARY KEY
	(VARIABLES_ID);

ALTER TABLE CHART_GRAPHIC ADD CONSTRAINT FK_CHART_GR_REFERENCE_REPORT FOREIGN KEY
	(REPORT_ID)
	REFERENCES REPORT
	(REPORT_ID);

ALTER TABLE COLUMNS ADD CONSTRAINT SYS_FK_55 FOREIGN KEY
	(REPORT_ID)
	REFERENCES REPORT
	(REPORT_ID);

ALTER TABLE CONTEXT_HELP ADD CONSTRAINT SYS_FK_51 FOREIGN KEY
	(MENU_CONTROL_ID)
	REFERENCES MENU_CONTROL
	(MENU_CONTROL_ID);

ALTER TABLE FIELDS ADD CONSTRAINT SYS_FK_63 FOREIGN KEY
	(REPORT_ID)
	REFERENCES REPORT
	(REPORT_ID);

ALTER TABLE GROUPS ADD CONSTRAINT SYS_FK_67 FOREIGN KEY
	(REPORT_ID)
	REFERENCES REPORT
	(REPORT_ID);

ALTER TABLE GROUP_COLUMNS ADD CONSTRAINT SYS_FK_81 FOREIGN KEY
	(GROUPS_ID)
	REFERENCES GROUPS
	(GROUPS_ID);

ALTER TABLE ORDERS ADD CONSTRAINT SYS_FK_89 FOREIGN KEY
	(CUSTOMER_ID)
	REFERENCES CUSTOMER
	(CUSTOMER_ID);

ALTER TABLE ORDERS_ITENS ADD CONSTRAINT SYS_FK_94 FOREIGN KEY
	(ORDERS_ID)
	REFERENCES ORDERS
	(ORDERS_ID);

ALTER TABLE ORDERS_ITENS ADD CONSTRAINT SYS_FK_95 FOREIGN KEY
	(PRODUCT_ID)
	REFERENCES PRODUCT
	(PRODUCT_ID);

ALTER TABLE PARAMETERS ADD CONSTRAINT SYS_FK_59 FOREIGN KEY
	(REPORT_ID)
	REFERENCES REPORT
	(REPORT_ID);

ALTER TABLE SERIES_COLUMNS ADD CONSTRAINT FK_SERIES_C_REFERENCE_CHART_GR FOREIGN KEY
	(CHART_GRAPHIC_ID)
	REFERENCES CHART_GRAPHIC
	(CHART_GRAPHIC_ID);

ALTER TABLE VARIABLES ADD CONSTRAINT SYS_FK_71 FOREIGN KEY
	(REPORT_ID)
	REFERENCES REPORT
	(REPORT_ID);

ALTER TABLE VARIABLES ADD CONSTRAINT SYS_FK_72 FOREIGN KEY
	(INCREMENT_GROUP_ID)
	REFERENCES GROUPS
	(GROUPS_ID);

ALTER TABLE VARIABLES ADD CONSTRAINT SYS_FK_73 FOREIGN KEY
	(RESET_GROUP_ID)
	REFERENCES GROUPS
	(GROUPS_ID);

